### ISSUE TITLE
Looks like CI isn't running the tests or code coverage

### ISSUE THREAD

**Issue by rusu24edward** [LLNL/SSAPy#14]
ci.yml has [the following lines](https://github.com/LLNL/SSAPy/blob/9ed512efdc889c030e26c45470a1d68ea24da1ea/.github/workflows/ci.yml#L66-L71):

```
    - name: Upload coverage reports to Codecov
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == 3.12
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: LLNL/SSAPy
```

Actions report [no coverage report](https://github.com/LLNL/SSAPy/actions/runs/10275935161/job/28435494568#step:6:52)

Recommend @rusu24edward for this issue
